// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9LrH7wpZTnEmv0-0e1mnIudSFt9pHVF8',
    appId: '1:814560666523:web:107f60a6db2eb876fef73e',
    messagingSenderId: '814560666523',
    projectId: 'altfit-4fd45',
    authDomain: 'altfit-4fd45.firebaseapp.com',
    storageBucket: 'altfit-4fd45.firebasestorage.app',
    measurementId: 'G-CX0M00XB34',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmXgdaGM4lL9ahrYEPtwmGBnzSjqyoZyc',
    appId: '1:814560666523:android:40f01ea94e270b1cfef73e',
    messagingSenderId: '814560666523',
    projectId: 'altfit-4fd45',
    storageBucket: 'altfit-4fd45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP1l08Ee8BGNrnBSUy_nUom-b8bKWgop4',
    appId: '1:814560666523:ios:94f69ffc62b9a2effef73e',
    messagingSenderId: '814560666523',
    projectId: 'altfit-4fd45',
    storageBucket: 'altfit-4fd45.firebasestorage.app',
    iosBundleId: 'com.example.altfit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP1l08Ee8BGNrnBSUy_nUom-b8bKWgop4',
    appId: '1:814560666523:ios:94f69ffc62b9a2effef73e',
    messagingSenderId: '814560666523',
    projectId: 'altfit-4fd45',
    storageBucket: 'altfit-4fd45.firebasestorage.app',
    iosBundleId: 'com.example.altfit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9LrH7wpZTnEmv0-0e1mnIudSFt9pHVF8',
    appId: '1:814560666523:web:df0ce94d1228ae07fef73e',
    messagingSenderId: '814560666523',
    projectId: 'altfit-4fd45',
    authDomain: 'altfit-4fd45.firebaseapp.com',
    storageBucket: 'altfit-4fd45.firebasestorage.app',
    measurementId: 'G-W9K4MQEYF1',
  );
}
